### ISSUE TITLE
Tracking issue for Sodium Plus v3

### ISSUE THREAD

**Issue by RedstoneWizard08** [happyredstone/sodiumplus#34]
As you may have noticed, there is a [`v3` branch](https://github.com/happyredstone/sodiumplus/tree/v3) in Sodium Plus. I'm working on a Fabric/Forge (using Embeddium for Sodium < 0.6) 1.20.x/1.21.x (and maybe 1.19.x, I don't know yet) compatible version of Sodium Plus with automatic releases for every version. This is the tracking issue for this feature.

We do plan to have the pack on CurseForge, too, by the way.

- [x] Reorganize the repo
- [x] Create a bootstrapper
- [x] Create a universal set of configs and resource packs
- [ ] Modify existing tooling to run through each supported version and loader
- [ ] Modify existing tooling to publish to Modrinth and CurseForge
- [ ] Modify existing tooling to merge universal and version-specific data at build time
- [ ] Modify existing tooling to add a utility to update mods for every version, reporting unavailable mods in respective log files
- [ ] Bring all supported platforms up-to-date with the `main` branch's changes
- [x] Add support for 1.20/Fabric
- [ ] Add support for 1.20/Forge
- [x] Add support for 1.20.1/Fabric
- [ ] Add support for 1.20.1/Forge
- [ ] Add support for 1.20.2/Fabric
- [ ] Add support for 1.20.2/Forge
- [ ] Add support for 1.20.3/Fabric
- [ ] Add support for 1.20.3/Forge
- [ ] Add support for 1.20.4/Fabric
- [ ] Add support for 1.20.4/Forge
- [ ] Add support for 1.20.5/Fabric
- [ ] Add support for 1.20.5/Forge
- [ ] Add support for 1.20.6/Fabric
- [ ] Add support for 1.20.6/Forge
- [ ] Add support for 1.21/Fabric
- [ ] Add support for 1.21/Forge
- [ ] Add support for 1.21.1/Fabric
- [ ] Add support for 1.21.1/Forge
- [ ] Add support for 1.21.2/Fabric
- [ ] Add support for 1.21.2/Forge
- [ ] Add support for 1.21.3/Fabric
- [ ] Add support for 1.21.3/Forge
- [ ] Add support for 1.21.4/Fabric
- [ ] Add support for 1.21.4/Forge

**Comment by RedstoneWizard08** [comment]
For the lovely people of Discord and whoever is watching this issue: Development of v3 is now happening in an internal repo (a copy of this one). That's not to say it won't be open-source -- as soon as we are done with it, it'll be in the public repo again. We just want to allow it to incubate further internally before a full release (I also have a couple of plans leading up to that). I'll try to remain transparent about some of our progress over on Discord. Happy crafting, everyone! :)

P.S. I'll still use this issue as a tracking issue.

**Comment by WONDEDWOLF** [comment]
hi guys can you add armor hud and status effect timer to the pack please 
                                                                                          THANKYOU
                  WAITING FOR YOUR RESPONSE

**Comment by juliandavidmedinapineros-arch** [comment]
Hola disculpen, intente jugar pero el juego no inicio y me aparecio este mensaje, que puedeo hacer?
Sodium Plus crashed without a crash report. The logs have been uploaded to `gnomebot.dev`:
### [latest.log](<https://gnomebot.dev/paste/mclogs/dTYsTXv>)   |   [stderr_stream.log](<https://gnomebot.dev/paste/mclogs/PiO4Avf>)   |   [crash_assistant_app.log](<https://gnomebot.dev/paste/mclogs/UHYXm4l>)   |   [win_event1773262496271.txt](<https://gnomebot.dev/paste/mclogs/KTQWkhL>)   |   [modlist.txt](<https://gnomebot.dev/paste/mclogs/LIjMXcs>)

### Mod list changes on top of the modpack:
```ansi
[2;34mMod list was not modified.[0m
```
